### ISSUE TITLE
there are multiple records with the same zip code

### ISSUE THREAD

**Issue by davdenic** [onlime/SwissZipCodeResolver#2]
Hello, 
I found this very useful, but unfortunately there are many records with the same zipcode.
Some of them are in different cantons.
For example with zipcode 3206 there are 5 records, 4 in canton BE and 1 in canton FR.
Maybe lookup should return an array with all results?

Thanks

**Comment by onlime** [comment]
Thanks @davdenic. I know I know. This project was abondoned in favor of [aternus/geonames-client](https://github.com/Aternus/geonames-client) which uses [GeoNames](http://www.geonames.org/) data.
I recommend using that one as it supports current international data and is very easy to use.
